version: '3.0'

services:
  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    hostname: nginx-proxy
    restart: unless-stopped
    volumes:
      - ./nginx-proxy/data:/data
      - ./nginx-proxy/letsencrypt:/etc/letsencrypt:z
    environment:
      - TZ=Asia/Seoul
    ports:
      - 80:80
      - 443:443
      - 50081:81
    networks:
      myserver:
        ipv4_address: 172.18.1.102
  gerrit:
    image: gerritcodereview/gerrit:3.8.0-ubuntu22
    user: root
    hostname: gerrit
    container_name: gerrit
    ports:
      - "29418:29418"
    volumes:
      - ./gerrit/db:/var/gerrit/db
      - ./gerrit/etc:/var/gerrit/etc
      - ./gerrit/git:/var/gerrit/git
      - ./gerrit/index:/var/gerrit/index
      - ./gerrit/plugins:/var/gerrit/plugins
    environment:
      - CANONICAL_WEB_URL=http://swjbs.com:8101
    networks:
      myserver:
        ipv4_address: 172.18.1.103
  apache:
    image: httpd
    user: root
    hostname: apache
    container_name: apache
    volumes:
      - ./apache2/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache2/httpd/.htpasswd:/usr/local/apache2/conf/.htpasswd
      - ./apache2/home:/usr/local/apache2/htdocs/
    ports:
      - "8100:80"
    networks:
      myserver:
        ipv4_address: 172.18.1.104
  gerrit_apache:
    image: httpd
    user: root
    hostname: gerrit_apache
    container_name: gerrit_apache
    volumes:
      - ./gerrit_apache2/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./gerrit_apache2/httpd/.htpasswd:/usr/local/apache2/conf/.htpasswd
    ports:
      - "8101:80"
    networks:
      myserver:
        ipv4_address: 172.18.1.105
  jenkins:
    privileged: true
    hostname : jenkins
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - './jenkins/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      TZ: "Asia/Seoul"
    networks:
      myserver:
        ipv4_address: 172.18.1.106
  mariadb:
    container_name: "mariadb"
    image: mariadb:10
    restart: always
    ports:
        - 3306:3306
    volumes:
        - "./mariadb/conf.d:/etc/mysql/conf.d"
        - "./mariadb/data:/var/lib/mysql"
    environment:
        TZ: "Asia/Seoul"
        MARIADB_DATABASE: "administrator"
        MARIADB_USER: "pon98142"
        MARIADB_PASSWORD: 72008364
        MARIADB_ROOT_PASSWORD: 72008364
    restart: always
    networks:
      myserver:
        ipv4_address: 172.18.1.107
networks:
  myserver:
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.100/16

